Added delete post functionality (Issue #6)
Pylons/pyramid_blogr pull request #67
Opened 2019-05-09 21:58 UTC by kenlittleton

Per Issue #6, added delete post functionality for current version (v1.9).

Also updated README.txt with reminder to source virtual env in shell.

2019-05-10 00:38 UTC, stevepiercy requested changes
Please make the requested changes. Thank you!

2019-05-10 00:38 UTC, stevepiercy commented on README.txt
> +
Please remove. There are other problems which I describe in #68, and this just complicates it.

2019-05-10 00:38 UTC, stevepiercy commented on pyramid_blogr/security.py
> +               (Allow, Authenticated, "delete"), ]
Please use quotation marks that are consistent with the previous.

2019-05-10 00:38 UTC, stevepiercy commented on pyramid_blogr/views/blog.py
> +    return HTTPFound(location=request.route_url("home"))
Please use single quote marks, consistent with the rest of the code.

2019-05-10 05:49 UTC, kenlittleton commented
Requested changes completed - forgot to disable black formatting before commit.

2019-05-10 05:50 UTC, kenlittleton commented on README.txt
> +
Can o worms - sorry, removed...

2019-05-10 12:03 UTC, stevepiercy approved these changes
Heh, I assumed this was Black in action, which we use in [Pyramid](https://github.com/Pylons/pyramid/blob/master/tox.ini) via `tox -e black`, but for entire files not just changes in commits.

2019-05-13 16:34 UTC, kenlittleton commented
Closed without merge. Published documentation would need to change.

2019-05-13 16:34 UTC, closed without merging